In [1]:
import numpy as np
from tomo2mesh.projects.eaton.rw_utils import read_raw_data_1X
from tomo2mesh.projects.eaton.void_mapping import void_map_all


In [2]:
projs, theta, center, dark, flat = read_raw_data_1X("1", "2")

In [3]:
V_seg = void_map_all(projs, theta, center, dark, flat, 1, 3.13, 0, 1151)

100%|███████████████████████████████████████████| 36/36 [01:46<00:00,  2.97s/it]


	TIME: RECONSTRUCTION 106.92 secs


In [5]:
import cc3d
from tomo2mesh.misc.voxel_processing import TimerCPU


In [6]:
timer = TimerCPU("secs")

In [16]:
timer.tic()
Vl_cc3d = cc3d.connected_components(V_seg)
t_cc3d = timer.toc("using cc3d")

	TIME: using cc3d 24.96 secs


In [19]:
Vl_cc3d.max()

206554

In [12]:
from scipy.ndimage import label as label_cpu

In [14]:
timer.tic()
Vl, n_det = label_cpu(V_seg,structure = np.ones((3,3,3),dtype=np.uint8))
t_ndimage = timer.toc("using ndimage")

	TIME: using ndimage 78.62 secs


In [15]:
n_det

206554

In [18]:
np.sum(Vl_cc3d == Vl)/Vl.size

1e+00

In [5]:
start_layer = 100
end_layer = 105
for ii, layer in enumerate(range(start_layer, end_layer+1)): 
    print(ii)
    print(layer)

0
100
1
101
2
102
3
103
4
104
5
105


In [60]:
import numpy as np
dust_thresh = 4
V_seg = np.array([np.random.randint(0, 100, size=(3, 3, 3)),np.random.randint(0, 100, size=(4, 4, 4)),np.random.randint(0, 100, size=(5, 5, 5))])
[np.sum(i) for i in V_seg if np.all(np.clip(i.shape-np.array((dust_thresh,dust_thresh,dust_thresh)), 0, None))==True][0]


/tmp/ipykernel_31646/4142784488.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  V_seg = np.array([np.random.randint(0, 100, size=(3, 3, 3)),np.random.randint(0, 100, size=(4, 4, 4)),np.random.randint(0, 100, size=(5, 5, 5))])


5732

In [52]:
V_seg = np.array([np.random.randint(0, 100, size=(3, 3, 3)),np.random.randint(0, 100, size=(4, 4, 4)),np.random.randint(0, 100, size=(5, 5, 5))])
V_seg[0]


/tmp/ipykernel_31646/1485280358.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  V_seg = np.array([np.random.randint(0, 100, size=(3, 3, 3)),np.random.randint(0, 100, size=(4, 4, 4)),np.random.randint(0, 100, size=(5, 5, 5))])


array([[[73, 58, 69],
        [16, 54, 95],
        [57, 17, 66]],

       [[20, 97,  4],
        [66, 69, 43],
        [94, 97, 54]],

       [[49, 87, 56],
        [94, 20, 14],
        [ 4, 19,  7]]])

In [40]:
np.all(np.clip(V_seg.shape-np.array((dust_thresh,dust_thresh,dust_thresh)), 0, None))

False

In [59]:
import numpy as np
import cc3d
Vr = np.random.randint(0,2,(10,10))
print(Vr, "\n")
V = cc3d.connected_components(Vr)
print(V, "\n")
V = cc3d.dust(V, threshold = 4, connectivity=4)
print(V, "\n")
V = (V>0).astype(np.uint8)
print(V, "\n")

[[0 0 0 1 1 1 1 0 0 1]
 [0 0 1 0 1 0 0 0 1 1]
 [0 1 0 0 1 1 0 0 0 1]
 [0 0 1 0 0 1 1 1 0 0]
 [1 0 1 1 0 1 0 1 0 0]
 [1 0 0 0 1 1 1 1 0 0]
 [1 0 0 0 1 1 0 1 0 1]
 [0 1 0 1 1 0 1 0 0 1]
 [1 1 0 1 1 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0]] 

[[0 0 0 1 1 1 1 0 0 2]
 [0 0 1 0 1 0 0 0 2 2]
 [0 1 0 0 1 1 0 0 0 2]
 [0 0 1 0 0 1 1 1 0 0]
 [3 0 1 1 0 1 0 1 0 0]
 [3 0 0 0 1 1 1 1 0 0]
 [3 0 0 0 1 1 0 1 0 4]
 [0 3 0 1 1 0 1 0 0 4]
 [3 3 0 1 1 0 0 0 4 0]
 [0 0 0 0 0 1 0 0 0 0]] 

[[0 0 0 1 1 1 1 0 0 2]
 [0 0 0 0 1 0 0 0 2 2]
 [0 0 0 0 1 1 0 0 0 2]
 [0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 0 1 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] 

[[0 0 0 1 1 1 1 0 0 1]
 [0 0 0 0 1 0 0 0 1 1]
 [0 0 0 0 1 1 0 0 0 1]
 [0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 0 1 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] 



In [23]:
V[1].shape

(512, 512)

In [35]:
from scipy import ndimage as ndimage_cpu
V = np.random.randint(0,2,(10,10))
print(V)
V,a = ndimage_cpu.label(V)
print(V)

[[1 1 1 0 1 1 1 1 0 0]
 [1 1 0 1 1 1 1 0 0 1]
 [1 0 0 0 1 1 0 0 1 0]
 [1 0 1 0 1 0 0 0 0 1]
 [0 1 0 0 0 0 1 1 1 0]
 [1 1 0 1 0 0 1 1 1 1]
 [1 1 0 0 1 0 1 0 1 1]
 [1 1 0 1 0 1 1 1 1 0]
 [0 0 0 0 0 1 0 1 1 1]
 [0 1 1 1 1 1 0 1 1 1]]
[[ 1  1  1  0  2  2  2  2  0  0]
 [ 1  1  0  2  2  2  2  0  0  3]
 [ 1  0  0  0  2  2  0  0  4  0]
 [ 1  0  5  0  2  0  0  0  0  6]
 [ 0  7  0  0  0  0  8  8  8  0]
 [ 7  7  0  9  0  0  8  8  8  8]
 [ 7  7  0  0 10  0  8  0  8  8]
 [ 7  7  0 11  0  8  8  8  8  0]
 [ 0  0  0  0  0  8  0  8  8  8]
 [ 0  8  8  8  8  8  0  8  8  8]]
